name: Build
permissions:
  contents: write

on:
  push:
  pull_request:

jobs:
  build:
    name: Build executable
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - run: |
        git fetch --prune --unshallow --tags
        git checkout $(git describe --tags $(git rev-list --tags --max-count=1))

    - run: pipx install poetry

    - uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        cache: 'poetry'

    - run: poetry install

    - if: matrix.os == 'ubuntu-latest'
      run: |
        shopt -s expand_aliases
        . ./envr.ps1
        build

    - if: matrix.os == 'windows-latest'
      run: |
        . ./envr.ps1
        build
    
    - name: Get name of the portable build
      id: get_name
      shell: bash
      run:  echo "BUILD_NAME=$(ls dist | grep smpmgr-.*\.zip)" >> $GITHUB_OUTPUT
    
    - name: Upload portable build 🚀
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/${{ steps.get_name.outputs.BUILD_NAME }}
        tag: ${{ github.ref }}
